name: Test Rust Starter Kit

on:
  workflow_call:
    inputs:
      rust_toolchain:
        type: string
        default: "1.83.0"
        required: false
      wasi_target:
        type: string
        default: "wasm32-wasi"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@${{ inputs.rust_toolchain }}

      - name: Add WASI Rust target
        run: rustup target add ${{ inputs.wasi_target }}  --toolchain ${{ inputs.rust_toolchain }}

      - name: Install rustfmt
        run: rustup component add rustfmt
        shell: bash

      - name: Install clippy
        run: rustup component add clippy
        shell: bash

      - name: Install cargo-audit
        run: cargo install cargo-audit
        shell: bash

      - name: Check binaries and format
        run: RUSTFLAGS="--deny warnings" cargo check --bins --target ${{ inputs.wasi_target }} && cargo fmt -- --check
        shell: bash

      - name: clippy
        run: cargo clippy
        shell: bash

      - name: audit
        run: cargo audit
        shell: bash

      - name: build
        run: cargo build
        shell: bash
