name: Generate changelog entry for Dependabot

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub token
        id: github-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ inputs.repository }}

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ steps.github-token.outputs.token }}

      - name: Generate changelog entry
        uses: dangoslen/dependabot-changelog-helper@v4
        with:
          activationLabels: dependencies
          changelogPath: './CHANGELOG.md'
          entryPrefix: 'build(deps): '

      - name: Commit changelog entry
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "docs(CHANGELOG.md): add dependency bump from dependabot"
