on:
  workflow_call:
    inputs:
      expected_pkg_name:
        description: >
          Expected package.json name. If provided, must match.
        type: string
        required: false

      expected_pkg_version:
        description: >
          Expected package.json version. If provided, must match.
          May include optional leading 'v' (e.g. v1.2.3).
        type: string
        required: false

      dist_tag:
        description: 'Dist tag to release e.g., latest, alpha, beta, rc, etc.'
        type: string
        required: false

      dry_run:
        description: 'Run all checks but do not actually publish packages.'
        type: boolean
        required: false
        default: false

      cwd:
        description: >
          Working directory containing package.json (relative to repo root).
        type: string
        required: false
        default: "."

      runner_label:
        description: 'Label for the runner to be used for the jobs.'
        default: 'ubuntu-latest'
        type: string
        required: false

jobs:
  publish-javascript-npmjs:
    runs-on: ${{ inputs.runner_label }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm dependencies
        shell: bash
        run: npm ci

      - name: Publish to npmjs.org
        id: publish_npmjs
        uses: fastly/devex-reusable-workflows/actions/publish-javascript-npmjs-v1@kats/publish-javascript-packages
        with:
          expected_pkg_name: ${{ inputs.expected_pkg_name }}
          expected_pkg_version: ${{ inputs.expected_pkg_version }}
          dist_tag: ${{ inputs.dist_tag }}
          dry_run: ${{ inputs.dry_run }}
          cwd: ${{ inputs.cwd }}

      - name: Publish status
        if: always()
        shell: bash
        run: |
          set -euo pipefail

          if [[ '${{ inputs.dry_run }}' == 'true' ]]; then
            echo "::notice::Dry run enabled — no package was actually published."
            exit 0
          fi

          OUTCOME="${{ steps.publish_npmjs.outcome }}"
          echo "npmjs outcome: ${OUTCOME:-skipped}"
          if [[ "${{ steps.publish_npmjs.outcome }}" == 'failure' ]]; then
            echo "::error::Publish to npmjs.org failed."
            echo "::notice::Hint: Ensure that the caller repo/workflow is registered as a Trusted Publisher in npm."
            exit 1
          fi
